[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[dev]
  command = "npm run start"

[[plugins]]
  package = "netlify-plugin-algolia-export"
    [plugins.inputs]
      exclude = ['/404.html', '/privacy-policy/indx.hmtl', '/delivery/index.html', '/contact-us/index.html', '/returns/index.hmtl', '/faqs/index.html']
