---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/site/posts
  label: Blog
  create: documents
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - blog-post
upload_dir: https://res.cloudinary.com/dwgql9lwg/image/upload
public_path: https://res.cloudinary.com/dwgql9lwg/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - STOREFRONT_API_TOKEN=cfec3febd330e764f5ecf98c6b9a5a44
  - STOREFRONT_API_URL=https://luna-creates.myshopify.com/api/2020-07/graphql.json
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
